### ISSUE TITLE
Aggiungere nota su foglio di stile personalizzato per slide

### ISSUE THREAD

**Issue by aborruso** [aborruso/revealjs-start#3]
```
<!-- .slide: data-background="./imgs/mappaConteggiCirc.jpg"  data-state="tabella" -->
```

E poi nel CSS 

```css
html.tabella table {
	background-color: rgba(44, 44, 44, 0.4);
}
```
